# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np

x = np.arange(25, dtype=int).reshape(5,5)
x = np.full_like(x, 0)
x[0,:] = x[:,0] = x[:,-1] =  x[-1,:] = 6
x

array([[6, 6, 6, 6, 6],
       [6, 0, 0, 0, 6],
       [6, 0, 0, 0, 6],
       [6, 0, 0, 0, 6],
       [6, 6, 6, 6, 6]])

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
x = np.zeros((8, 8), dtype = int)
# x[row(row:column:step), column(row:column:step)]
x[::2, 1::2] = 9
x[::2, ::2] = 3
x[1::2, ::2] = 9
x[1::2, 1::2] = 3
x

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
print(np.empty((4,3)))
print(np.full((3, 3), 6))

[[6.89822846e-310 4.65521314e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
#c = 5(f - 32)/9
#f = ((9c/5) + 32)
arr = np.array([0, 12, 45.21 ,34, 99.91])
func = lambda x: (x - 32) / (9 / 5)
np.array([func(i) for i in arr])


array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
arr = np.array([ 1.00000000+0.j, 0.70710678+0.70710678j])
print("Real part of the array-")
print(arr.real)
print("Imaginary part of the array-")
print(arr.imag)

Real part of the array-
[1.         0.70710678]
Imaginary part of the array-
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [6]:
np.intersect1d([ 0, 10, 20, 40, 60],[10, 30, 40] )

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [7]:
print(np.unique([10, 10, 20, 20, 30, 30]))

print(np.unique([[1, 1],[2, 3]]))

[10 20 30]
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [8]:

arr1 = [0, 10, 20, 40, 60, 80]
arr2 = [10, 30, 40, 50, 70]
np.setxor1d(arr1, arr2)

array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [9]:
arr1 = [1,2,0]
arr2 = [1,2,3]

print(np.all(arr1))
print(np.all(arr2))

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [10]:
arr1 = [[1,2],[1,0]]

np.all(arr1, axis=1)

array([ True, False])

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [11]:
arr = np.array([1, 2, 3, 4])

print(np.tile(arr, 2))
print(np.tile(arr, 3))

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [12]:
arr = [1, 2, 3, 4, 5, 6]

np.amax(arr)

print("Maximum Values-" + str(np.where(arr == np.amax(arr))[0][0]))
print("Minimum Values-" + str(np.where(arr == np.amin(arr))[0][0]))

Maximum Values-5
Minimum Values-0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [13]:
arr1 = [1,2]
arr2 = [4,5]

np.all(arr1 == arr2)

False

Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [14]:
arr = np.array([[4,6],[2,1]])
np.sort(arr, axis=0) #first axis
np.sort(arr) # last axis


array([[4, 6],
       [1, 2]])

Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [15]:
arr = np.array([[ 0, 10, 20],
    [20, 30, 40]])

print(arr[arr>10])
print(np.nonzero(arr > 10))

[20 20 30 40]
(array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [16]:

arr = np.array([1,2,3])
arr.size * arr.itemsize

24

## Great Job!